on:
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: self-hosted
    environment: DEV
    name: A job to deploy UCD application
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            deployment.properties
          sparse-checkout-cone-mode: false
      - name: Deploy UCD application
        id: Deploy_MYAPP
        uses: bharathk-github/UrbanCodeDeployAction@vtest-1.23
        with:
          application: 'MYAPP'
          applicationProcess: 'Install'
          environment: 'DEV'
          propertiesfile: 'deployment.properties'
          snapshot: 'snapshot-2'
          versions: '[{"version": "TEMP1-JCLA", "component": "MYCOMP"},{"version": "File1","component": "Regular component"},{"version": "file2","component": "Regular component"}]'
          hostname: '${{ secrets.UCD_HOST }}'
          authToken: '${{ secrets.AUTH_TOKEN }}'
