on:
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: self-hosted
    environment: DEV
    name: A job to deploy UCD application
    steps:
      - name: Deploy UCD application
        id: Deploy_MYAPP
        uses: bharathk-github/UrbanCodeDeployAction@v1.23
        with:
          application: 'MYAPP'
          applicationProcess: 'Install'
          environment: 'DEV'
          properties: '{"prop1":"${{ vars.PROP1 }}", "prop2":"${{ vars.PROP2 }}"}'
          snapshot: 'snapshot-2'
          versions: '[{"version": "TEMP1-JCLA", "component": "MYCOMP"},{"version": "File1","component": "Regular component"},{"version": "file2","component": "Regular component"}]'
          hostname: '${{ secrets.UCD_HOST }}'
          authToken: '${{ secrets.AUTH_TOKEN }}'
